<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class OwnerData extends Model
{
    use HasFactory;

    protected $fillable = [
        'insured_version_acc',
        'insured_occupation',
        'rc_owner_name',
        'vehicle_no',
        'made_make',
        'engine_no',
        'chass_no',
        'class_of_vehicle',
        'details_opp_vehicle',
        'permit_details',
        'owner_opp_vehicle',
        'fitness_validity_from',
        'fitness_validity_to',
        'polution_validity_from',
        'polution_validity_to',
        'doa_in_policy',
        'policy_comper_tp_liability',
        'if_goodladen_details',
        'damage_goods_transport',
        'details_damage_vehicle',
        'insured_advocate',
        'accused_admited_offence',
        'type_license',
        'vehicle_auth_drive',
        'mismatch_vehicle_in_dl',
        'insured_advocate_num',
        'all_liability_covered',
        'is_close_proximity',
        'rc_owner_insurer_same',
        'victim_is_employee',
        'reg_valid_doa',
        'fitness_valid_doa',
        'valid_permit_doa',
        'any_violation_route_permit',
        'opp_party_insurer_name',
        'opp_party_policy_no',
        'is_opp_party_liabile',
        'opp_party_period_insurance',
        'opp_part_class_vehicle',
        'opp_party_rc_owner',
        'opp_engine_no',
        'opp_chassis_no',
        'cc_vehicle',
        'opp_party_cc_vehicle',
        'address_mobile_accused',
        'accused_dl_vaild_doa',
        'rel_accused_insured',
        'opp_driver_dl_valid',
        'accused_accident_before',
        'dl_no_owner',
        'dl_no_opp_vehicle',
        'opp_party_class_vehicle_auth_drive',
        'accused_first_issue_nt',
        'opp_party_first_issue_nt',
        'nt_validity__accused',
        'nt_validity_opp_party',
        'badge_no_accused',
        'badge_no_opp_party',
        'accused_tv_first_issue',
        'opp_party_tv_first_issue',
        'accused_transport_validity',
        'opp_party_transport_validity',
        'interact_no',
        'accident_hapn_nat_hoilday',
        'date_claim_intimated',
        'reason_late_intimation',
        'insured_profession',
        'is_neg_area_address',
        'pan_no_owner',
        'aadhar_no_owner',
        'hyp_details',
        'vehicle_damages',
        'comercl_vehicle_details',
        'material_loss_accidnt',
        'material_quantity',
        'is_load_recept_available',
        'fitness_details',
        'area_covered',
        'prev_insurer',
        'prev_policy_no',
        'policy_detl',
        'any_clain_in_prev_policy',
        'is_prev_claim_photo_available',
        'social_status'
    ];
}
